class Movie {
  static List<Movie> getMovies() => [
        Movie(
            "Avatar",
            "2009",
            "PG-19",
            "2009",
            "162 min",
            "Action, Adventure, Fantasy",
            "James Cameron",
            "Sam Worthington",
            "Zoe Saldana",
            "On the lush alien world of Pandora live the Na'vi, beings who appear primitive but are highly evolved. Because the planet's environment is poisonous, human/Na'vi hybrids, called Avatars, must link to human minds to allow for free movement on Pandora.",
            "English, Spanish",
            "USA, UK",
            "Won 3 Oscars. Another 80 wins & 121 nominations.",
            "https://upload.wikimedia.org/wikipedia/en/b/b0/Avatar-Teaser-Poster.jpg",
            "83",
            "7.9",
            "890,617",
            "tt0499549",
            "movie",
            "True", [
          "https://upload.wikimedia.org/wikipedia/en/b/b0/Avatar-Teaser-Poster.jpg",
          "https://cnet1.cbsistatic.com/img/BI1FWxAVLKOz7wQn0OK6z2aNe78=/1200x675/2019/01/11/b251bf04-5bf8-469a-be8d-79489551460b/avatar-2009.jpg",
          "https://www.deeperblue.com/wp-content/uploads/2017/12/Avatar-2-What-We-Know-1068x562.jpg",
          "https://s3.amazonaws.com/ffe-ugc/avatar/assets/3b1e2506-b839-11e7-883d-000d3a3122f5_w_1024w.jpg?v=38",
          "https://www.indiewire.com/wp-content/uploads/2019/12/avatar-2.jpg"
        ]),
        Movie(
            "The Martian",
            "2015",
            "PG-19",
            "2015",
            "162 min",
            "Action, Drama, Sci-Fi",
            "Ridley Scott",
            "Sam Worthington",
            " Matt Damon, Jessica Chastain, Kristen Wiig",
            "On the lush alien world of Pandora live the Na'vi, beings who appear primitive but are highly evolved. Because the planet's environment is poisonous, human/Na'vi hybrids, called Avatars, must link to human minds to allow for free movement on Pandora.",
            "English, Spanish",
            "USA, UK",
            "Nominated for 7 Oscars. Another 40 wins & 188 nominations.",
            "https://upload.wikimedia.org/wikipedia/commons/5/56/Mountain_in_Wadi_Rum%2C_Jordan.jpg",
            "83",
            "8.0",
            "890,617",
            "tt0499549",
            "movie",
            "True", [
          "https://upload.wikimedia.org/wikipedia/en/c/cd/The_Martian_film_poster.jpg",
          "https://upload.wikimedia.org/wikipedia/commons/0/04/International_Space_Station_after_undocking_of_STS-132.jpg",
          "https://upload.wikimedia.org/wikipedia/commons/a/a7/PIA19913-MarsLandingSite-Ares3Mission-TheMartian-2015Film-20150517.jpg",
          "https://upload.wikimedia.org/wikipedia/commons/5/56/Mountain_in_Wadi_Rum%2C_Jordan.jpg",
          "https://en.wikipedia.org/wiki/The_Martian_(film)#/media/File:Jessica_Chastain_TIFF_2015.jpg"
        ]),
        Movie(
            "Mission Impossible",
            "2015",
            "PG-19",
            "2015",
            "162 min",
            "Action, Adventure, Thriller",
            "J. J. Abrams ",
            "Sam Worthington",
            "Tom Cruise, Rebecca Ferguson, Jeremy Renner",
            "On the lush alien world of Pandora live the Na'vi, beings who appear primitive but are highly evolved. Because the planet's environment is poisonous, human/Na'vi hybrids, called Avatars, must link to human minds to allow for free movement on Pandora. ",
            "English, Spanish",
            "USA, UK",
            "Won 6 Oscars. Another 24 wins & 40 nominations.",
            "https://upload.wikimedia.org/wikipedia/en/b/bc/Mission_Impossible_III.jpg",
            "83",
            "7.4",
            "890,617",
            "tt0499549",
            "movie",
            "True", [
          "https://upload.wikimedia.org/wikipedia/en/b/bc/Mission_Impossible_III.jpg",
          "https://www.indiewire.com/wp-content/uploads/2017/06/mission-impossible.jpg",
          "https://m.media-amazon.com/images/M/MV5BMTY4MTUxMjQ5OV5BMl5BanBnXkFtZTcwNTUyMzg5Ng@@._V1_.jpg",
          "https://www.justinkownacki.com/wp-content/uploads/2018/08/Mission-Impossible-Fallout-1200.jpg",
          "https://d2j1wkp1bavyfs.cloudfront.net/wp-content/uploads/2018/07/6_Fallout.jpg"
        ]),
        Movie(
            "Fast & Furious 8",
            "2001",
            "PG-19",
            "2017",
            "162 min",
            "Action, Adventure, Fantasy",
            "F. Gary Gray",
            "Sam Worthington",
            " Vin Diesel, Jason Statham, Dwayne Johnson",
            "On the lush alien world of Pandora live the Na'vi, beings who appear primitive but are highly evolved. Because the planet's environment is poisonous, human/Na'vi hybrids, called Avatars, must link to human minds to allow for free movement on Pandora. ",
            "English, Spanish",
            "USA, UK",
            "Won 1 Oscars. Another 7 wins & 21 nominations.",
            "https://upload.wikimedia.org/wikipedia/en/2/2d/The_Fate_of_The_Furious_Theatrical_Poster.jpg",
            "83",
            "6.7",
            "890,617",
            "tt0499549",
            "movie",
            "True", [
          "https://upload.wikimedia.org/wikipedia/en/2/2d/The_Fate_of_The_Furious_Theatrical_Poster.jpg",
          "https://static.toiimg.com/thumb/msid-58194296,imgsize-63148,width-800,height-600,resizemode-75/58194296.jpg",
          "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQGI-Bls3bDKSDqt_0QgG201hyo4jz0NoS2uw&usqp=CAU",
          "https://cdn.collider.com/wp-content/uploads/2016/06/fast-8-tej-car.png",
          "https://www.tflcar.com/wp-content/uploads/2016/12/fast-and-furious-8-f8-movie.png"
        ]),
        Movie(
            "A Quite Place",
            "2018",
            "PG-19",
            "2018",
            "70 min",
            "Drama, Horror, Sci-Fi",
            "John Krasinski",
            "Sam Worthington",
            " Emily Blunt, John Krasinski, Millicent Simmonds",
            "On the lush alien world of Pandora live the Na'vi, beings who appear primitive but are highly evolved. Because the planet's environment is poisonous, human/Na'vi hybrids, called Avatars, must link to human minds to allow for free movement on Pandora. ",
            "English, Spanish",
            "USA, UK",
            "Won 3 Oscars. Another 80 wins & 121 nominations.",
            "https://upload.wikimedia.org/wikipedia/en/0/02/A_Quiet_Place_Part_II.jpg",
            "83",
            "7.3",
            "890,617",
            "tt0499549",
            "movie",
            "True", [
          "https://upload.wikimedia.org/wikipedia/en/0/02/A_Quiet_Place_Part_II.jpg",
          "https://www.syfy.com/sites/syfy/files/2018/04/aqp_18441r.jpg",
          "https://img.cinemablend.com/quill/b/0/f/1/3/d/b0f13d8206e936bf1513f472f985d76ffbc19583.jpg",
          "https://img.jakpost.net/c/2018/04/04/2018_04_04_43296_1522824740._large.jpg",
          "https://i.insider.com/5e346df1ab49fd22ea180485?width=1100&format=jpeg&auto=webp"
        ]),
        Movie(
            "Inception",
            "2010",
            "PG-19",
            "2010",
            "162 min",
            "Action, Adventure, Sci-Fi",
            "Christopher Nolan",
            "Sam Worthington",
            "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
            "On the lush alien world of Pandora live the Na'vi, beings who appear primitive but are highly evolved. Because the planet's environment is poisonous, human/Na'vi hybrids, called Avatars, must link to human minds to allow for free movement on Pandora. ",
            "English, Spanish",
            "USA, UK",
            "Won 4 Oscars. Another 152 wins & 218 nominations.",
            "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
            "83",
            "8.8",
            "890,617",
            "tt0499549",
            "movie",
            "True", [
          "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
          "https://miro.medium.com/max/800/1*Aop38tMyxWjGowYDVX4Nqw@2x.jpeg",
          "https://pyxis.nymag.com/v1/imgs/fa8/345/620c78a00c83d6583328f6e0e06599f28b-inception.jpg",
          "https://m.media-amazon.com/images/M/MV5BMTQ1ZmIzOTAtNDcwZi00NDVkLWE4NWItYWNhZGY1MmVlZGU0XkEyXkFqcGdeQWRvb2xpbmhk._V1_CR1,0,1904,1071_AL_UX477_CR0,0,477,268_AL_.jpg",
          "https://pyxis.nymag.com/v1/imgs/7a6/e81/589a9ad6a788b44e1f7008ce3a57c1ca60-inception-1.jpg"
        ]),
        Movie(
            "Interstellar",
            "2014",
            "PG-19",
            "2014",
            "148 min",
            "Drama, Adventure, Sci-Fi",
            "Cristopher Nolan",
            "Sam Worthington",
            " Matthew McConaughey, Anne Hathaway, Jessica Chastain",
            "On the lush alien world of Pandora live the Na'vi, beings who appear primitive but are highly evolved. Because the planet's environment is poisonous, human/Na'vi hybrids, called Avatars, must link to human minds to allow for free movement on Pandora. ",
            "English, Spanish",
            "USA, UK",
            "Won 1 Oscars. Another 43 wins & 148 nominations.",
            "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
            "83",
            "8.6",
            "890,617",
            "tt0499549",
            "movie",
            "True", [
          "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
          "https://cdn.collider.com/wp-content/uploads/2019/05/interstellar-poster-2.jpg",
          "https://lwlies.com/wp-content/uploads/2016/01/interstellar-review.jpg",
          "https://i2.wp.com/exandor.com/wp-content/uploads/2017/10/Interstellar-1.jpg?fit=1030%2C644&ssl=1",
          "https://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2014/11/5/1415201794019/Matthew-McConaughey-in-In-014.jpg?width=700&quality=85&auto=format&fit=max&s=7ca85dcd8787f3c9ff63fb2213085f40"
        ]),
        Movie(
            "Arrival",
            "2016",
            "PG-19",
            "2016",
            "116 min",
            "Drama, Mystery, Sci-Fi",
            "Denis Villeneuve",
            "Sam Worthington",
            "Amy Adams, Jeremy Renner, Forest Whitaker ",
            "On the lush alien world of Pandora live the Na'vi, beings who appear primitive but are highly evolved. Because the planet's environment is poisonous, human/Na'vi hybrids, called Avatars, must link to human minds to allow for free movement on Pandora. ",
            "English, Spanish",
            "USA, UK",
            "Won 1 Oscars. Another 67 wins & 263 nominations.",
            "https://images-na.ssl-images-amazon.com/images/I/81fvNfPZBsL._RI_.jpg",
            "83",
            "7.9",
            "890,617",
            "tt0499549",
            "movie",
            "True", [
          "https://images-na.ssl-images-amazon.com/images/I/81fvNfPZBsL._RI_.jpg",
          "https://i.ytimg.com/vi/tFMo3UJ4B4g/maxresdefault.jpg",
          "https://www.zastavki.com/pictures/originals/2017Movies_Louise_and_Ian_film_characters_Arrival_112271_.jpg",
          "https://s.studiobinder.com/wp-content/uploads/2010/03/Arrival-Video-Essay-How-to-Balance-Fear-and-Intrigue-WP.jpg",
          "https://cdn.vox-cdn.com/thumbor/724eDMipcb3l75w9CcLaHZkax7E=/1400x0/filters:no_upscale()/cdn.vox-cdn.com/uploads/chorus_asset/file/7469421/ArrivalAdamsRenner.jpg"
        ]),
        Movie(
            "Sherlock Holmes",
            "2009",
            "PG-19",
            "2009",
            "128 min",
            "Action, Adventure, Mystery",
            "Sir Arthur Conan Doyle.",
            "Sam Worthington",
            " Robert Downey Jr., Jude Law, Rachel McAdams",
            "On the lush alien world of Pandora live the Na'vi, beings who appear primitive but are highly evolved. Because the planet's environment is poisonous, human/Na'vi hybrids, called Avatars, must link to human minds to allow for free movement on Pandora. ",
            "English, Spanish",
            "USA, UK",
            "Nominated for 2 Oscars. Another 10 wins & 29 nominations.",
            "https://img.etimg.com/thumb/msid-68266481,width-1200,height-900,imgsize-584851,overlay-etpanache/photo.jpg",
            "83",
            "7.6",
            "890,617",
            "tt0499549",
            "movie",
            "True", [
          "https://img.etimg.com/thumb/msid-68266481,width-1200,height-900,imgsize-584851,overlay-etpanache/photo.jpg",
          "https://cdn.britannica.com/04/84704-050-7E762815/Basil-Rathbone-movies-Arthur-Conan-Doyle-one.jpg",
          "https://i.pinimg.com/736x/bf/18/4c/bf184c45e4b9dc385010052ee121c19f.jpg",
          "https://lh3.googleusercontent.com/proxy/gny-6jhAaoa13AZ4_0y-5O4rJ27tg4pWB5nLbAy9DC8KWDHZk-kGFHwtZY0aLn_CLHpkjqY6ld9nuAy-6QY6wxjbEyEQmCrx1fDPy77k2TaIfcPPu6hzsQtfwgUfA4-vuhXyyCGFB90",
          "https://images.csmonitor.com/csmarchives/2009/12/1223-Film-Review-Sherlock-Holmes.jpg?alias=standard_900x600"
        ]),
        Movie(
            "Call of the Wilde",
            "2020",
            "PG-19",
            " 2020",
            "100 min",
            "Drama, Adventure, Family",
            "Chris Sanders,",
            "Sam Worthington",
            "Harrison Ford, Omar Sy, Cara Gee",
            "On the lush alien world of Pandora live the Na'vi, beings who appear primitive but are highly evolved. Because the planet's environment is poisonous, human/Na'vi hybrids, called Avatars, must link to human minds to allow for free movement on Pandora. ",
            "English, Spanish",
            "USA, UK",
            "Nominated for 1 Oscars. Another 1 wins & 7 nominations.",
            "https://cineplexbd.com/uploads/movie_gallery/portrait/wild1.jpg",
            "83",
            "6.8",
            "890,617",
            "tt0499549",
            "movie",
            "True", [
          "https://cineplexbd.com/uploads/movie_gallery/portrait/wild1.jpg",
          "https://i1.wp.com/360mode.net/wp-content/uploads/2020/05/call.jpg?fit=800450&ssl=1",
          "https://d23.com/app/uploads/2020/02/780w-463h_022020_the-call-of-the-wild-feature-3.jpg",
          "https://i1.wp.com/360mode.net/wp-content/uploads/2020/05/call.jpg?fit=800450&ssl=1",
          "https://m.media-amazon.com/images/M/MV5BZDA1ZmQ2OGMtZDhkMC00ZjRkLWE3ZTMtMzA5ZTk0YjM1OGRmXkEyXkFqcGdeQXVyNzI1NzMxNzM@._V1_.jpg"
        ]),
        Movie(
            "Tears of the Sun",
            "2003",
            "PG-19",
            " 2003",
            "130 min",
            "Action, Drama, Thriller",
            " Antoine Fuqua.",
            "Sam Worthington",
            "Bruce Willis, Cole Hauser, Monica Bellucci",
            "On the lush alien world of Pandora live the Na'vi, beings who appear primitive but are highly evolved. Because the planet's environment is poisonous, human/Na'vi hybrids, called Avatars, must link to human minds to allow for free movement on Pandora. ",
            "English, Spanish",
            "USA, UK",
            "Won 0 Oscars. Another 0 wins & 2 nominations.",
            "https://images.moviesanywhere.com/2151d16181ca5a147c8d789a1a0610c7/13975e32-3cf7-4124-be93-f4ad479061a1.jpg",
            "83",
            "6.6",
            "890,617",
            "tt0499549",
            "movie",
            "True", [
          "https://images.moviesanywhere.com/2151d16181ca5a147c8d789a1a0610c7/13975e32-3cf7-4124-be93-f4ad479061a1.jpg",
          "https://mundoairsofter.com/wp-content/uploads/2012/08/Lake-Tears-of-the-sun-kit-list.jpg",
          "https://m.media-amazon.com/images/M/MV5BNTg3NDQxNTI3OF5BMl5BanBnXkFtZTYwMzY1MTA3._V1_.jpg",
          "https://resizing.flixster.com/d7U9W2De8xRFMb87kQMpoiMYk3c=/864x648/v1.bjs5NjM5Mzg7ajsxODU1MTsxMjAwOzg2NDs2NDg",
          "https://i.pinimg.com/originals/af/e9/bc/afe9bcedcff8a92b357d06ae2f4425fc.jpg"
        ]),
      ];

  //all the properties of avatar movie
  String title;
  String year;
  String rated;
  String released;
  String runtime;
  String genre;
  String director;
  String writer;
  String actors;
  String plot;
  String language;
  String country;
  String awards;
  String poster;
  String metascore;
  String imdbRating;
  String imdbVotes;
  String imdbID;
  String type;
  String response;
  List<String> images;

  //Constructor for above property
  Movie(
      this.title,
      this.year,
      this.rated,
      this.released,
      this.runtime,
      this.genre,
      this.director,
      this.writer,
      this.actors,
      this.plot,
      this.language,
      this.country,
      this.awards,
      this.poster,
      this.metascore,
      this.imdbRating,
      this.imdbVotes,
      this.imdbID,
      this.type,
      this.response,
      this.images);
}
